### ISSUE TITLE
Hardware acceleration error

### ISSUE THREAD

**Issue by cah-dante-taylor** [amrsa1/Android-Emulator-Docker#3]
Hello,
I am experiencing a hardware acceleration error when running the instructions below. Any advice on how to correct this error? 

![image](https://user-images.githubusercontent.com/110122470/217353546-dcdf792f-f482-4d2f-a844-b8870f9dcb63.png)

**Comment by amrsa1** [comment]
Chould you define whats you operating system ?

Do you have vtd enabled in your bios config ?

**Comment by cah-dante-taylor** [comment]
Yes the Operating system is as follows 
![image](https://user-images.githubusercontent.com/110122470/217371501-d41321da-ef01-41d1-8e53-339a25d60166.png)
![image](https://user-images.githubusercontent.com/110122470/217371621-117229dd-39c1-4a83-a064-14541021187b.png)

Vtd is enabled 
![image](https://user-images.githubusercontent.com/110122470/217371800-d554b838-a723-419f-98ec-d127a246a965.png)

**Comment by amrsa1** [comment]
@cah-dante-taylor
Please try the updated version 

https://hub.docker.com/repository/docker/amrka/android-emulator/general

**Comment by cah-dante-taylor** [comment]
Hello just giving some updates, the error is still persisting. Is there a way to update the emulator version? It seems that the version specified is not compatible. Also the ini file that the error is displaying is indicating that its missing a configuration within the file that allows it to boot.

**Comment by amrsa1** [comment]
Hi @cah-dante-taylor 

could you run this command:

emulator @nexus -no-snapshot-load --gpu off 

if you get same error try this 

emulator @nexus -no-snapshot-load -gpu off -accel off

**Comment by cah-dante-taylor** [comment]
![image](https://user-images.githubusercontent.com/110122470/217909827-1bd047f0-c3a0-4d29-bd50-534c63628b30.png)
Hello I used the above commands and was able to get the emulator to show. This is the result.

**Comment by amrsa1** [comment]
Add there flag as well

--no-boot-anim

And give it a couple of mins to boot up

**Comment by cah-dante-taylor** [comment]
![image](https://user-images.githubusercontent.com/110122470/218137208-a6553b32-eb8a-4b76-9940-a5cb07a5ac9e.png)
![image](https://user-images.githubusercontent.com/110122470/218137960-0a561def-3f3a-4c96-ba6f-2662f3cc31e4.png)

Hello, after running the commands I have noticed several errors and warnings while the emulator is booting up. Are these normal? And also will the same steps performed work if running the emulator in headless mode?

**Comment by amrsa1** [comment]
> ![image](https://user-images.githubusercontent.com/110122470/218137208-a6553b32-eb8a-4b76-9940-a5cb07a5ac9e.png)
> ![image](https://user-images.githubusercontent.com/110122470/218137960-0a561def-3f3a-4c96-ba6f-2662f3cc31e4.png)
> 
> Hello, after running the commands I have noticed several errors and warnings while the emulator is booting up. Are these normal? And also will the same steps performed work if running the emulator in headless mode?

Nothing to worry about as long as the emulator is running, i see only warnings in the screenshot  so it should be fine, anyway will push and updated version very soon.


If you dont have any further concerns please close the ticket.
